//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Advertisers = new HashSet<Advertiser>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int adminid { get; set; }
        public string adminname { get; set; }
        public string password { get; set; }
        public int userid { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Advertiser> Advertisers { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
