//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Clients = new HashSet<Client>();
            this.Packages = new HashSet<Package>();
        }
    
        public int employeeid { get; set; }
        public string employeename { get; set; }
        public string password { get; set; }
        public string type { get; set; }
        public double salary { get; set; }
        public string mobilenumber { get; set; }
        public string address { get; set; }
        public int adminid { get; set; }
        public int userid { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual ICollection<Client> Clients { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Package> Packages { get; set; }
    }
}
