//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int pid { get; set; }
        public string pname { get; set; }
        public string ptype { get; set; }
        public string plocation { get; set; }
        public double pprice { get; set; }
        public System.DateTime creationdate { get; set; }
        public System.DateTime expiredate { get; set; }
        public int employeeid { get; set; }
        public int clientid { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
